//! `agentstack completions <shell>` — tab completion for bash, zsh and fish.
//!
//! The script is generated by walking the live clap tree, the same trick
//! `self docs` uses for the command inventory (see [`super::self_cmd`]), so
//! completion can never drift from the real surface. Deliberately NOT built on
//! `clap_complete`: that would be a new dependency for something a hundred
//! lines of table-walking already covers.
//!
//! What it completes, and nothing more: command names, nested subcommand names,
//! and long flags. Values (paths, toolset names, harness ids) are left to the
//! shell's own file completion — promising more would mean shelling back out to
//! `agentstack` on every keystroke, and a completion that lies is worse than
//! one that stops short.

use anyhow::Result;
use clap::CommandFactory;

use crate::cli::{Cli, CompletionsArgs, Shell};

/// One node of the completion table: a full command path as the user types it
/// (`agentstack`, `agentstack lib`, `agentstack self docs`) mapped to every
/// word that may legally follow it.
struct Node {
    path: String,
    words: Vec<String>,
}

pub fn run(args: &CompletionsArgs) -> Result<()> {
    let nodes = nodes();
    let script = match args.shell {
        Shell::Bash => bash(&nodes),
        Shell::Zsh => zsh(&nodes),
        Shell::Fish => fish(&nodes),
    };
    print!("{script}");
    Ok(())
}

/// Flatten the clap tree into one node per command path, root first.
fn nodes() -> Vec<Node> {
    let mut out = Vec::new();
    walk(&Cli::command(), "agentstack".to_string(), &mut out);
    out
}

fn walk(cmd: &clap::Command, path: String, out: &mut Vec<Node>) {
    let mut words: Vec<String> = Vec::new();
    // Subcommands, declaration order. Hidden ones are included for the same
    // reason the docs inventory includes them: they run, they have their own
    // `--help`, and a completion that omits them is just an incomplete map.
    // `help` is clap's auto-command and completing it helps nobody.
    for sub in cmd.get_subcommands() {
        if sub.get_name() != "help" {
            words.push(sub.get_name().to_string());
        }
    }
    // Long flags, including the global ones (clap propagates those to every
    // subcommand, so they really are valid here). `help`/`version` are clap's
    // auto-args — `--help` is re-added below for every node so a node is never
    // word-less, which is what makes "is this a known path?" answerable in the
    // generated shell script with a single non-empty test.
    for arg in cmd.get_arguments() {
        if arg.is_hide_set() {
            continue;
        }
        if let Some(long) = arg.get_long() {
            if long != "help" && long != "version" {
                words.push(format!("--{long}"));
            }
        }
    }
    words.push("--help".to_string());
    if cmd.get_version().is_some() {
        words.push("--version".to_string());
    }
    out.push(Node {
        path: path.clone(),
        words,
    });
    for sub in cmd.get_subcommands() {
        if sub.get_name() == "help" {
            continue;
        }
        walk(sub, format!("{path} {}", sub.get_name()), out);
    }
}

// ── Script emitters ─────────────────────────────────────────────────────────
//
// All three scripts share one shape: a `words <path>` lookup table generated
// from [`nodes`], plus a few lines that walk the words already typed to find
// the deepest known path and complete from that node. Non-flag words that are
// NOT a known subcommand (a toolset name, a file) stop the walk without
// resetting it, so flags still complete after a positional.
//
// Command and flag names come from our own clap tree — ASCII identifiers — so
// they are emitted inside single quotes without further escaping.

fn bash(nodes: &[Node]) -> String {
    let mut out = String::from(
        "# agentstack bash completion — generated by `agentstack more completions bash`.\n\
         \n\
         _agentstack_words() {\n    \
             case \"$1\" in\n",
    );
    for node in nodes {
        out.push_str(&format!(
            "        '{}') echo '{}' ;;\n",
            node.path,
            node.words.join(" ")
        ));
    }
    out.push_str(
        "        *) echo '' ;;\n    \
             esac\n\
         }\n\
         \n\
         _agentstack() {\n    \
             local cur path next i word\n    \
             cur=\"${COMP_WORDS[COMP_CWORD]}\"\n    \
             path=\"agentstack\"\n    \
             for (( i = 1; i < COMP_CWORD; i++ )); do\n        \
                 word=\"${COMP_WORDS[i]}\"\n        \
                 case \"$word\" in -*) continue ;; esac\n        \
                 next=\"$path $word\"\n        \
                 if [ -n \"$(_agentstack_words \"$next\")\" ]; then\n            \
                     path=\"$next\"\n        \
                 else\n            \
                     break\n        \
                 fi\n    \
             done\n    \
             COMPREPLY=( $(compgen -W \"$(_agentstack_words \"$path\")\" -- \"$cur\") )\n\
         }\n\
         \n\
         complete -F _agentstack agentstack\n",
    );
    out
}

fn zsh(nodes: &[Node]) -> String {
    let mut out = String::from(
        "#compdef agentstack\n\
         # agentstack zsh completion — generated by `agentstack more completions zsh`.\n\
         \n\
         _agentstack_words() {\n    \
             case \"$1\" in\n",
    );
    for node in nodes {
        out.push_str(&format!(
            "        '{}') echo '{}' ;;\n",
            node.path,
            node.words.join(" ")
        ));
    }
    out.push_str(
        "        *) echo '' ;;\n    \
             esac\n\
         }\n\
         \n\
         _agentstack() {\n    \
             # NOT named `path`: in zsh that is a special array tied to $PATH,\n    \
             # and declaring it `local` keeps the tie, so assigning a command\n    \
             # path to it would blank $PATH for the whole completion call.\n    \
             local cmdpath next word raw\n    \
             local -a candidates\n    \
             integer i\n    \
             cmdpath=\"agentstack\"\n    \
             for (( i = 2; i < CURRENT; i++ )); do\n        \
                 word=\"${words[i]}\"\n        \
                 [[ \"$word\" == -* ]] && continue\n        \
                 next=\"$cmdpath $word\"\n        \
                 if [[ -n \"$(_agentstack_words \"$next\")\" ]]; then\n            \
                     cmdpath=\"$next\"\n        \
                 else\n            \
                     break\n        \
                 fi\n    \
             done\n    \
             raw=\"$(_agentstack_words \"$cmdpath\")\"\n    \
             candidates=( ${=raw} )\n    \
             compadd -a candidates\n\
         }\n\
         \n\
         _agentstack \"$@\"\n",
    );
    out
}

fn fish(nodes: &[Node]) -> String {
    let mut out = String::from(
        "# agentstack fish completion — generated by `agentstack more completions fish`.\n\
         \n\
         function __agentstack_words\n    \
             switch \"$argv[1]\"\n",
    );
    for node in nodes {
        out.push_str(&format!(
            "        case '{}'\n            echo '{}'\n",
            node.path,
            node.words.join(" ")
        ));
    }
    out.push_str(
        "        case '*'\n            echo ''\n    \
             end\n\
         end\n\
         \n\
         function __agentstack_complete\n    \
             set -l tokens (commandline -opc)\n    \
             # Drop the binary name. Guarded: `set -e` on an index a short list\n    \
             # doesn't have is an error in fish, not a no-op.\n    \
             if test (count $tokens) -gt 1\n        \
                 set -e tokens[1]\n    \
             else\n        \
                 set tokens\n    \
             end\n    \
             set -l path 'agentstack'\n    \
             for tok in $tokens\n        \
                 if string match -q -- '-*' $tok\n            \
                     continue\n        \
                 end\n        \
                 set -l next \"$path $tok\"\n        \
                 set -l found (__agentstack_words \"$next\")\n        \
                 if test -n \"$found\"\n            \
                     set path $next\n        \
                 else\n            \
                     break\n        \
                 end\n    \
             end\n    \
             __agentstack_words \"$path\" | string split ' '\n\
         end\n\
         \n\
         complete -c agentstack -f -a '(__agentstack_complete)'\n",
    );
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The table is generated from the live tree, so the witness is structural:
    /// the root node exists, nesting is captured, and a subcommand promoted or
    /// renamed in cli.rs shows up here without anyone editing this file.
    #[test]
    fn nodes_cover_the_tree_root_and_its_nesting() {
        let nodes = nodes();
        let root = nodes.first().expect("root node");
        assert_eq!(root.path, "agentstack");
        assert!(root.words.iter().any(|w| w == "doctor"));
        assert!(root.words.iter().any(|w| w == "--manifest-dir"));
        assert!(root.words.iter().any(|w| w == "--version"));

        let nested = nodes
            .iter()
            .find(|n| n.path == "agentstack self docs")
            .expect("nested subcommand paths are in the table");
        assert!(nested.words.iter().any(|w| w == "--write"));

        // Every node is non-empty: the generated scripts use "the table
        // returned something" as their is-this-a-known-path test.
        assert!(nodes.iter().all(|n| !n.words.is_empty()));
        // `help` is clap's auto-command, not surface worth completing.
        assert!(!nodes.iter().any(|n| n.path.ends_with(" help")));
    }

    /// Each script must actually name the shell machinery its shell needs —
    /// a silent typo here produces a file that sources cleanly and completes
    /// nothing.
    #[test]
    fn each_script_carries_its_shell_entrypoint() {
        let nodes = nodes();
        let b = bash(&nodes);
        assert!(b.contains("complete -F _agentstack agentstack"));
        assert!(b.contains("'agentstack doctor')"));

        let z = zsh(&nodes);
        assert!(z.starts_with("#compdef agentstack"));
        assert!(z.contains("compadd -a candidates"));
        // `path` is special in zsh — tied to $PATH, and `local` keeps the tie.
        // Using it as the walk variable blanks $PATH for the whole completion
        // call, so the script must not declare one.
        assert!(!z.contains("local path"));

        let f = fish(&nodes);
        assert!(f.contains("complete -c agentstack -f -a '(__agentstack_complete)'"));
        assert!(f.contains("case 'agentstack doctor'"));
    }
}
