//! `agentstack codemode` — generate the typed code-mode client for this
//! project's proxied MCP servers (PLAN code-mode Phase 2). Read-only by default
//! (shows what it would write); `--write` materializes the agentstack-owned,
//! contained files under `.agentstack/codemode/`.
//!
//! The generated client is secret-free: each function forwards a call to the
//! loopback runtime endpoint `agentstack mcp` exposes, which resolves `${REF}`s
//! per call. agentstack never runs the agent's code — the harness does.

use std::path::Path;

use anyhow::{Context, Result};
use owo_colors::OwoColorize;

use crate::cli::CodemodeArgs;

/// `endpoint.json` is machine-local (loopback port + one-time token) and must
/// never be committed; the rest of the client is reproducible and secret-free.
const GITIGNORE: &str = "# generated by `agentstack codemode`\n\
    # endpoint.json holds this machine's loopback port + token — never commit it.\n\
    endpoint.json\n";

pub fn run(args: &CodemodeArgs, manifest_dir: Option<&Path>) -> Result<()> {
    let gateway = crate::gateway::Gateway::from_manifest(manifest_dir);
    let servers = gateway.proxied_servers();

    if servers.is_empty() {
        println!("No HTTP MCP servers to proxy in this project — nothing to generate.");
        println!("Add one with `agentstack add server …` (gateway v1 is HTTP-only), then re-run.");
        return Ok(());
    }

    let bindings = gateway.generate_bindings();
    let tool_count = gateway.namespaced_tools().len();
    let cmdir = crate::codemode::codemode_dir(manifest_dir);

    // Secret-health summary — the `explain` view of the runtime surface.
    println!(
        "Code-mode client for {} proxied server(s), {tool_count} tool(s):",
        servers.len()
    );
    for (name, unresolved) in &servers {
        if unresolved.is_empty() {
            println!("  • {name} — secrets resolve here");
        } else {
            println!(
                "  • {name} — {} unresolved secret(s): {} (calls refused until set with `agentstack secret set`)",
                unresolved.len(),
                unresolved.join(", ")
            );
        }
    }
    println!();

    let files: [(&str, &str); 3] = [
        ("client.ts", bindings.client_ts.as_str()),
        ("agentstack-runtime.ts", bindings.runtime_ts.as_str()),
        (".gitignore", GITIGNORE),
    ];

    if !args.write {
        println!("Would write (dry-run — pass --write):");
        for (f, _) in &files {
            println!("  {}", cmdir.join(f).display());
        }
        println!(
            "\nBindings are secret-free (tool names only). Re-run with `--write` to materialize them."
        );
        return Ok(());
    }

    std::fs::create_dir_all(&cmdir).with_context(|| format!("creating {}", cmdir.display()))?;
    for (f, contents) in &files {
        let path = cmdir.join(f);
        crate::util::atomic::write(&path, contents)
            .with_context(|| format!("writing {}", path.display()))?;
    }
    println!(
        "{} wrote code-mode client to {}",
        "✓".green(),
        cmdir.display()
    );
    println!(
        "  Start `agentstack mcp` in this project (it serves the runtime endpoint), then import\n  the client and run your program with your harness's code tool."
    );
    Ok(())
}
