//! The image **plan**: which pinned members one toolset composes into, where
//! each lands inside the artifact, and every reason the build must refuse.
//!
//! `docs/design/packaging.md` is the contract. This module is the read half —
//! it opens the manifest, the lock, and the content store, and produces a
//! [`ImagePlan`] that is either buildable or carries the blockers saying why
//! not. It stages nothing and it builds nothing; `commands::image` does both.
//!
//! Three rules do most of the work here, and all three are borrowed rather
//! than invented:
//!
//! 1. **Members come from the lock, and their bytes come from the store by
//!    digest.** The live library directory is never read
//!    (`docs/design/pinned-serving-and-library-drift.md`).
//! 2. **The server set is the frozen, pin-verified one.** Exactly
//!    [`crate::resolve::frozen_runtime_servers`] — the same fail-closed set a
//!    sandbox run is assembled from, so an image can never contain a server a
//!    run would have refused.
//! 3. **No `${REF}` is ever resolved.** Nothing in this module constructs a
//!    secret resolver. What it collects is the set of NAMES a run must supply
//!    (`CLAUDE.md` invariant 5).

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use anyhow::{Context as _, Result};

use agentstack_core::lock::{Lock, PackageMemberKind};
use agentstack_core::manifest::Manifest;

use crate::commands::LibraryCtx;
use crate::resolve::FrozenServer;

/// The one root every AgentStack-contributed byte lands under, inside the
/// image. Everything below is relative to it — see `docs/design/packaging.md`
/// §"What an image is" for the layout.
pub const PAYLOAD_ROOT: &str = "/agentstack";

/// The payload's directory name inside the build context.
pub const PAYLOAD_DIR: &str = "agentstack";

/// `HOME` inside the image. Set explicitly rather than inherited, because the
/// harness finds its own skills directory by expanding `~` and the base
/// image's home is not knowable from here. Making it ours is what lets a skill
/// be laid down at a path the harness will actually look at.
pub const IMAGE_HOME: &str = "/agentstack/home";

/// The file the entrypoint reads: one `${REF}` NAME per line, never a value.
pub const REQUIRED_SECRETS_FILE: &str = "required-secrets";

/// The fail-closed run-time secret guard.
///
/// **This text is a compile-time constant and nothing is ever interpolated
/// into it** (`CLAUDE.md` invariant 7). The variable part of the job — which
/// names are required — lives in a data file the script reads; the script
/// itself is the same bytes in every image AgentStack builds.
///
/// `printenv "$ref"` rather than `eval`: the name arrives from a file, and a
/// file-derived name must be an *argument* to a program, never a fragment of a
/// program. `set -eu` plus `exit 78` (`EX_CONFIG`) make a missing secret a
/// refusal to start rather than a harness that comes up half-configured.
pub const ENTRYPOINT_SH: &str = r#"#!/bin/sh
# Generated by `agentstack image`. Fixed text: nothing from any project is
# interpolated into this script. See docs/design/packaging.md.
#
# Secrets are NEVER baked into an image. This checks that every ${REF} the
# toolset in this image declares is present in THIS run's environment, and refuses
# to start the harness if any is missing.
set -eu

refs_file=/agentstack/required-secrets
missing=''

if [ -f "$refs_file" ]; then
  while IFS= read -r ref || [ -n "$ref" ]; do
    [ -n "$ref" ] || continue
    if printenv "$ref" >/dev/null 2>&1; then
      :
    else
      missing="$missing $ref"
    fi
  done < "$refs_file"
fi

if [ -n "$missing" ]; then
  echo "agentstack: this image requires secrets that are not set:$missing" >&2
  echo "agentstack: pass them into the run (docker run -e NAME=...); they are" >&2
  echo "agentstack: never stored in the image." >&2
  exit 78
fi

exec "$@"
"#;

/// What kind of member this is. The three kinds a toolset can compose;
/// executable kinds (hooks, extensions) never appear, by construction — they
/// are not selectable by a toolset and never enter an image.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MemberKind {
    Skill,
    Server,
    Instruction,
}

impl MemberKind {
    pub fn as_str(self) -> &'static str {
        match self {
            MemberKind::Skill => "skill",
            MemberKind::Server => "server",
            MemberKind::Instruction => "instruction",
        }
    }
}

/// One pinned member that would enter the image.
#[derive(Debug, Clone)]
pub struct Member {
    pub kind: MemberKind,
    pub name: String,
    /// The lock's digest for this member's bytes, hex.
    pub digest: String,
    /// Where the bytes came from, for a human: `inline`, `library`,
    /// `package:<name>@<version>#…`.
    pub provenance: String,
    /// Absolute destination inside the image.
    pub dest: String,
    /// Whether the member's bytes are laid down where the harness itself reads
    /// them (skills), or carried under `/agentstack` for the runner (servers,
    /// instruction members). Reported so no surface can imply a carried member
    /// is a compiled one.
    pub compiled: bool,
}

/// Why the build must refuse. A blocker names the member it belongs to, so a
/// dry run can print the whole plan and still fail closed.
#[derive(Debug, Clone)]
pub struct Blocker {
    pub kind: &'static str,
    pub name: String,
    pub reason: String,
}

/// The complete answer for one `agentstack image` invocation.
pub struct ImagePlan {
    pub toolset: String,
    pub harness: String,
    pub harness_display: String,
    pub tag: String,
    pub base: String,
    pub members: Vec<Member>,
    /// The `${REF}` NAMES a run must supply. Never values, never resolved.
    pub required_secrets: Vec<String>,
    pub blockers: Vec<Blocker>,
    /// Where `--write` stages the build context.
    pub context_dir: PathBuf,
    /// The harness launch argv the image's `CMD` carries.
    pub cmd: Vec<String>,
    /// Absolute path, inside the image, of the harness's skills directory.
    pub skills_dest: Option<String>,
    /// The frozen server set, kept so the staging half does not re-resolve
    /// (one resolution, one truth — the rule `ExecutionPlan::build` follows).
    pub servers: Vec<FrozenServer>,
    /// Skill name → the verified store snapshot its bytes are copied from.
    pub skill_sources: Vec<(String, PathBuf)>,
    /// Instruction member name → the verified store snapshot deposit.
    pub instruction_sources: Vec<(String, PathBuf)>,
}

impl ImagePlan {
    pub fn buildable(&self) -> bool {
        self.blockers.is_empty()
    }

    /// The posture the artifact carries. Deliberately the SHIPPED
    /// `Posture::Sandbox` and not a fourth word: the artifact is prepared for
    /// the `--sandbox` contract, and posture is established by the run, never
    /// by the image. `docs/design/packaging.md` §"The posture label".
    pub fn posture(&self) -> crate::commands::sandbox::Posture {
        crate::commands::sandbox::Posture::Sandbox
    }

    /// The one sentence every surface uses for what the label does not
    /// promise. Written once so the terminal, the JSON, and the docs cannot
    /// drift apart.
    pub fn posture_caveat(&self) -> String {
        "posture belongs to the run, not the image — a bare `docker run` gets the container \
         boundary only: no egress proxy, no allowlist, no run log"
            .to_string()
    }

    pub fn to_json(&self) -> serde_json::Value {
        let posture = self.posture();
        serde_json::json!({
            "image": {
                "toolset": self.toolset,
                "harness": self.harness,
                "tag": self.tag,
                "base": self.base,
                "posture": {
                    "slug": posture.slug(),
                    "label": posture.to_string(),
                    "established_by": "run",
                    "caveat": self.posture_caveat(),
                },
                "members": self.members.iter().map(|m| serde_json::json!({
                    "kind": m.kind.as_str(),
                    "name": m.name,
                    "digest": m.digest,
                    "provenance": m.provenance,
                    "dest": m.dest,
                    "compiled": m.compiled,
                })).collect::<Vec<_>>(),
                "required_secrets": self.required_secrets,
                "blockers": self.blockers.iter().map(|b| serde_json::json!({
                    "kind": b.kind,
                    "name": b.name,
                    "reason": b.reason,
                })).collect::<Vec<_>>(),
                "buildable": self.buildable(),
                "context": self.context_dir.display().to_string(),
                "cmd": self.cmd,
            }
        })
    }
}

/// Which toolset this invocation is about.
///
/// A toolset must be NAMED — explicitly, or by the manifest having exactly
/// one. An image is a composition, and silently picking one of several would
/// make the artifact's identity a guess.
pub fn resolve_toolset(manifest: &Manifest, requested: Option<&str>) -> Result<String> {
    match requested {
        Some(name) => {
            anyhow::ensure!(
                manifest.profiles.contains_key(name),
                "no toolset '{name}' in this project — `agentstack toolset list` names the ones \
                 it has"
            );
            Ok(name.to_string())
        }
        None => {
            let mut names = manifest.profiles.keys();
            match (names.next(), names.next()) {
                (Some(only), None) => Ok(only.clone()),
                (Some(_), Some(_)) => anyhow::bail!(
                    "this project declares several toolsets — name the one to build an image from, with \
                     `--toolset <name>`"
                ),
                _ => anyhow::bail!(
                    "this project declares no toolset — an image is one toolset materialized, \
                     so create one first with `agentstack toolset create <name>`"
                ),
            }
        }
    }
}

/// Which harness the image launches: the flag, else the toolset's own
/// `harness`, else the project's single default target. Never a built-in
/// default — the image's `CMD` is the harness binary, and guessing it would
/// produce an artifact that starts the wrong thing.
pub fn resolve_harness(
    manifest: &Manifest,
    toolset: &str,
    requested: Option<&str>,
    registry: &crate::adapter::Registry,
    dir: &Path,
) -> Result<String> {
    let named = requested.map(str::to_string).or_else(|| {
        manifest
            .profiles
            .get(toolset)
            .and_then(|p| p.harness.clone())
    });
    if let Some(id) = named {
        anyhow::ensure!(
            registry.get(&id).is_some(),
            "unknown tool '{id}' — see `agentstack x adapters list`"
        );
        return Ok(id);
    }
    let targets = crate::render::resolve_targets(manifest, registry, &[], dir)?;
    match targets.as_slice() {
        [only] => Ok(only.clone()),
        _ => anyhow::bail!(
            "an image runs one tool, and this project targets {} — name it with \
             `--harness <id>`",
            crate::commands::count(targets.len(), "tool")
        ),
    }
}

/// Build the plan. Reads the lock and the store; resolves no secret, spawns
/// nothing, contacts nothing, writes nothing.
// The parameter cluster mirrors `resolve`'s resolution seams (manifest, dir,
// library, registry) plus the four things a caller chooses. Bundling them into
// a struct would only move the same list somewhere else, and taking `ImageArgs`
// directly would couple the read half to the clap surface.
#[allow(clippy::too_many_arguments)]
pub fn plan(
    manifest: &Manifest,
    dir: &Path,
    libctx: &LibraryCtx,
    registry: &crate::adapter::Registry,
    toolset: &str,
    harness: &str,
    tag: Option<&str>,
    base: Option<&str>,
) -> Result<ImagePlan> {
    // The toolset name becomes a path segment (the context dir) and a label
    // value, so it passes the shipped name contract before either.
    crate::text::validate_name(toolset).with_context(|| {
        format!(
            "refusing to build an image for toolset '{}'",
            toolset.escape_debug()
        )
    })?;

    let desc = registry
        .get(harness)
        .with_context(|| format!("unknown tool '{harness}' — see `agentstack x adapters list`"))?;
    let bin = desc
        .detect
        .bin
        .clone()
        .with_context(|| format!("{} has no known launch binary to run", desc.display))?;

    let lock = Lock::load(dir).unwrap_or_default();
    let store = &libctx.store;

    let mut members: Vec<Member> = Vec::new();
    let mut blockers: Vec<Blocker> = Vec::new();
    let mut skill_sources: Vec<(String, PathBuf)> = Vec::new();
    let mut instruction_sources: Vec<(String, PathBuf)> = Vec::new();

    // Where the harness reads skills from, inside the image. `SkillsSpec.dir`
    // is the adapter's own `~/…` spelling; re-anchoring it at the image's HOME
    // is the whole translation — we do not invent a layout the harness has
    // never heard of.
    let skills_dest = desc
        .skills
        .as_ref()
        .map(|s| rebase_home(&s.dir, IMAGE_HOME));

    // ── skills ────────────────────────────────────────────────────────────
    for name in crate::resolve::active_skill_names(manifest, toolset) {
        let Some(entry) = lock.get(&name) else {
            blockers.push(Blocker {
                kind: "skill",
                name: name.clone(),
                reason: "not pinned in agentstack.lock — an image is built from reviewed \
                         digests, so review with `agentstack lock`, then pin with `agentstack lock --write`"
                    .into(),
            });
            continue;
        };
        let hex = entry.checksum.hex();
        if !store.has_pinned_content(hex) {
            blockers.push(Blocker {
                kind: "skill",
                name: name.clone(),
                reason: format!(
                    "its approved bytes ({hex}) are not in the content store, or no longer \
                     hash to their own name — review the live content with `agentstack trust`"
                ),
            });
            continue;
        }
        let Some(dest) = skills_dest.as_ref() else {
            blockers.push(Blocker {
                kind: "skill",
                name: name.clone(),
                reason: format!(
                    "{} has no skills directory, so this skill would reach nothing inside \
                     the image",
                    desc.display
                ),
            });
            continue;
        };
        skill_sources.push((name.clone(), store.root().join("content").join(hex).clone()));
        members.push(Member {
            kind: MemberKind::Skill,
            name: name.clone(),
            digest: hex.to_string(),
            provenance: skill_provenance(entry),
            dest: format!("{dest}/{name}"),
            compiled: true,
        });
    }

    // Package-carried skill members ride the same rule.
    for (pkg, m) in crate::package::members_of_kind(&lock, PackageMemberKind::Skill, Some(toolset))
    {
        let hex = m.checksum.hex();
        if !store.has_pinned_content(hex) {
            blockers.push(Blocker {
                kind: "skill",
                name: m.name.clone(),
                reason: format!(
                    "package '{}' pins this member at {hex}, which the content store cannot \
                     verify — re-pin with `agentstack lock --write`",
                    pkg.name
                ),
            });
            continue;
        }
        let Some(dest) = skills_dest.as_ref() else {
            continue;
        };
        if members
            .iter()
            .any(|e| e.kind == MemberKind::Skill && e.name == m.name)
        {
            continue; // an inline declaration of the same name already won
        }
        skill_sources.push((m.name.clone(), store.root().join("content").join(hex)));
        members.push(Member {
            kind: MemberKind::Skill,
            name: m.name.clone(),
            digest: hex.to_string(),
            provenance: m.provenance.clone(),
            dest: format!("{dest}/{}", m.name),
            compiled: true,
        });
    }

    // ── servers ───────────────────────────────────────────────────────────
    // The SAME frozen, pin-verified set a sandbox run is assembled from, so an
    // image can never carry a server a run would have refused — and, since
    // review finding 1, that set includes the toolset's package members, so the
    // claim is now true of packages too. This used to append them here, which
    // made the sentence above false: the image carried servers no run served.
    let servers = crate::resolve::frozen_runtime_servers(
        manifest,
        &libctx.library,
        &libctx.lib_home,
        dir,
        Some(toolset),
    )?;

    let mut required: BTreeSet<String> = BTreeSet::new();
    for (name, resolved) in &servers {
        match resolved {
            Err(reason) => blockers.push(Blocker {
                kind: "server",
                name: name.clone(),
                reason: reason.clone(),
            }),
            Ok(rs) => {
                // Serialize the definition with `${REF}` placeholders intact —
                // this is exactly what `ResolvedServer::server` promises, and
                // it is the reason no resolver is constructed anywhere here.
                let text = serde_json::to_string_pretty(&rs.server)
                    .with_context(|| format!("serializing server '{name}'"))?;
                for r in agentstack_core::refs::refs_in(&text) {
                    required.insert(r);
                }
                members.push(Member {
                    kind: MemberKind::Server,
                    name: name.clone(),
                    digest: rs.checksum.clone(),
                    provenance: rs
                        .provenance
                        .clone()
                        .unwrap_or_else(|| format!("{:?}", rs.origin).to_lowercase()),
                    dest: format!("{PAYLOAD_ROOT}/servers/{name}.json"),
                    // Carried, not compiled: rendering a server definition into
                    // the harness's own config would resolve `${REF}` and write
                    // concrete values into a distributable artifact.
                    compiled: false,
                });
            }
        }
    }

    // ── package instruction members ───────────────────────────────────────
    for (pkg, m) in
        crate::package::members_of_kind(&lock, PackageMemberKind::Instruction, Some(toolset))
    {
        let hex = m.checksum.hex();
        match verified_fragment(store, hex) {
            Some(path) => {
                instruction_sources.push((m.name.clone(), path));
                members.push(Member {
                    kind: MemberKind::Instruction,
                    name: m.name.clone(),
                    digest: hex.to_string(),
                    provenance: m.provenance.clone(),
                    dest: format!("{PAYLOAD_ROOT}/instructions/{}", m.name),
                    // Carried, never compiled — see `docs/design/packaging.md`
                    // §"Deliberate limits" for why this is deliberate.
                    compiled: false,
                });
            }
            None => blockers.push(Blocker {
                kind: "instruction",
                name: m.name.clone(),
                reason: format!(
                    "package '{}' pins this member at {hex}, which the content store cannot \
                     verify — re-pin with `agentstack lock --write`",
                    pkg.name
                ),
            }),
        }
    }

    // A ref name is re-validated before it can be written into the artifact.
    // `refs_in` only yields valid names, so this can only fire if that
    // contract ever loosens — which is precisely when it should fire.
    for r in &required {
        anyhow::ensure!(
            agentstack_core::refs::is_ref_name(r),
            "refusing to record secret reference '{}' — not a valid ${{REF}} name",
            r.escape_debug()
        );
    }

    let base = base
        .map(str::to_string)
        .unwrap_or_else(crate::commands::sandbox::sandbox_image);
    let tag = tag
        .map(str::to_string)
        .unwrap_or_else(|| format!("agentstack/{toolset}:latest"));

    Ok(ImagePlan {
        toolset: toolset.to_string(),
        harness: harness.to_string(),
        harness_display: desc.display.clone(),
        tag,
        base,
        members,
        required_secrets: required.into_iter().collect(),
        blockers,
        context_dir: context_dir_for(toolset),
        cmd: vec![bin],
        skills_dest,
        servers,
        skill_sources,
        instruction_sources,
    })
}

/// Where `--write` stages a build context. Deterministic per toolset (it is
/// rewritten from scratch each build) and outside the project, because a
/// project must not gain generated files it never asked for.
pub fn context_dir_for(toolset: &str) -> PathBuf {
    crate::util::paths::agentstack_home()
        .join("images")
        .join(toolset)
        .join("context")
}

/// Re-anchor an adapter's `~/…` path at the image's own HOME. A path that is
/// already absolute is taken as-is — an adapter that names `/etc/…` means it.
fn rebase_home(dir: &str, home: &str) -> String {
    match dir.strip_prefix("~/") {
        Some(rest) => format!("{home}/{rest}"),
        None if dir == "~" => home.to_string(),
        None => dir.to_string(),
    }
}

fn skill_provenance(entry: &agentstack_core::lock::LockedSkill) -> String {
    use agentstack_core::lock::SkillLockSource;
    match entry.source {
        SkillLockSource::Path => entry
            .path
            .clone()
            .map(|p| format!("path:{p}"))
            .unwrap_or_else(|| "path".into()),
        SkillLockSource::Git => match (&entry.git, &entry.rev) {
            (Some(url), Some(rev)) => format!("git:{url}@{rev}"),
            (Some(url), None) => format!("git:{url}"),
            _ => "git".into(),
        },
    }
}

/// The single regular file a pinned instruction fragment's deposit holds, if
/// the deposit still hashes to its own name. `None` is the fail-closed answer
/// for anything else — missing, tampered, a directory of several files, or a
/// symlink.
fn verified_fragment(store: &crate::store::Store, hex: &str) -> Option<PathBuf> {
    let dest = store.root().join("content").join(hex);
    if !dest
        .symlink_metadata()
        .map(|m| m.file_type().is_dir())
        .unwrap_or(false)
        || crate::scan::reject_symlinks(&dest).is_err()
    {
        return None;
    }
    let entries: Vec<_> = std::fs::read_dir(&dest).ok()?.flatten().collect();
    let [only] = entries.as_slice() else {
        return None;
    };
    if !only.file_type().map(|t| t.is_file()).unwrap_or(false) {
        return None;
    }
    let bytes = std::fs::read(only.path()).ok()?;
    if agentstack_core::digest::sha256_hex(&bytes) != hex {
        return None;
    }
    Some(only.path())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn home_is_rebased_only_for_tilde_paths() {
        assert_eq!(
            rebase_home("~/.claude/skills", "/agentstack/home"),
            "/agentstack/home/.claude/skills"
        );
        assert_eq!(
            rebase_home("/opt/skills", "/agentstack/home"),
            "/opt/skills"
        );
    }

    /// The guard is a constant, and it must stay one: a build that could
    /// interpolate a project string into this script would be interpolating
    /// repository content into a shell (invariant 7).
    #[test]
    fn the_entrypoint_guard_interpolates_nothing_and_never_evals() {
        assert!(!ENTRYPOINT_SH.contains("eval"));
        assert!(ENTRYPOINT_SH.contains("printenv \"$ref\""));
        assert!(ENTRYPOINT_SH.contains("exit 78"));
        assert!(ENTRYPOINT_SH.contains("exec \"$@\""));
        // A format placeholder here would mean someone made it a template.
        assert!(!ENTRYPOINT_SH.contains("{}"));
    }
}
