//! Code mode (PLAN code-mode Phase 2): emit a typed client for the project's
//! proxied MCP servers so the agent can write one small program that calls
//! several upstream tools and runs it in **the harness's own sandbox**.
//!
//! agentstack does not execute the agent's code — it only *generates* the
//! bindings and *brokers* the actual MCP calls (via the gateway). The generated
//! client is secret-free: each function forwards `{ name, arguments }` to the
//! local runtime endpoint ([`endpoint`]), which resolves `${REF}`s at call time
//! and proxies the real upstream. This keeps agentstack a compiler that brokers
//! calls, never an arbitrary-code runtime.

pub mod endpoint;

use std::path::{Path, PathBuf};

use serde_json::Value;

/// The agentstack-owned directory the generated client lives in:
/// `<manifest_dir>/codemode/` (i.e. `.agentstack/codemode/`). Contained and
/// pruned like other rendered artifacts.
pub fn codemode_dir(manifest_dir: Option<&Path>) -> PathBuf {
    let base = manifest_dir
        .map(Path::to_path_buf)
        .unwrap_or_else(|| std::env::current_dir().unwrap_or_default());
    crate::manifest::resolve_manifest_dir(&base).join("codemode")
}

/// The two generated files of a project's code-mode client.
pub struct Bindings {
    /// `client.ts` — the typed, per-server function surface.
    pub client_ts: String,
    /// `agentstack-runtime.ts` — the thin shim every binding calls.
    pub runtime_ts: String,
}

/// Render the typed TS client from a gateway's namespaced tool list (each entry
/// is `{ name: "<server>__<tool>", description, inputSchema }`, exactly as
/// [`crate::gateway::Gateway::namespaced_tools`] produces).
///
/// Output is deterministic: servers and tools are sorted alphabetically so the
/// same proxied surface always renders byte-identical. Tools are grouped under a
/// single `codemode` object, addressed `codemode.<server>.<tool>(input)`.
pub fn render_client(tools: &[Value]) -> String {
    // Group by server, preserving each tool's (name, description, schema).
    type ToolEntry<'a> = (&'a str, &'a str, &'a Value);
    let mut servers: Vec<(&str, Vec<ToolEntry>)> = Vec::new();
    for t in tools {
        let name = t.get("name").and_then(Value::as_str).unwrap_or("");
        let Some((server, tool)) = name.split_once("__") else {
            continue;
        };
        let desc = t.get("description").and_then(Value::as_str).unwrap_or("");
        let schema = t.get("inputSchema").unwrap_or(&Value::Null);
        match servers.iter_mut().find(|(s, _)| *s == server) {
            Some((_, list)) => list.push((tool, desc, schema)),
            None => servers.push((server, vec![(tool, desc, schema)])),
        }
    }
    servers.sort_by(|a, b| a.0.cmp(b.0));
    for (_, list) in &mut servers {
        list.sort_by(|a, b| a.0.cmp(b.0));
    }

    let mut out = String::new();
    out.push_str(CLIENT_HEADER);
    if servers.is_empty() {
        out.push_str(
            "\n// This project proxies no HTTP MCP tools yet — add a server to the\n\
             // manifest, then regenerate with `agentstack codemode --write`.\n\
             export const codemode = {};\n",
        );
        return out;
    }
    out.push_str("\nexport const codemode = {\n");
    for (server, list) in &servers {
        out.push_str(&format!("  {}: {{\n", quote_key(server)));
        for (tool, desc, schema) in list {
            let full = format!("{server}__{tool}");
            out.push_str(&format!("    /** {} */\n", jsdoc(desc)));
            out.push_str(&format!(
                "    {}: (input: {}): Promise<unknown> =>\n      call({:?}, input),\n",
                quote_key(tool),
                ts_input_type(schema),
                full,
            ));
        }
        out.push_str("  },\n");
    }
    out.push_str("};\n");
    out
}

/// The runtime shim — static, secret-free. It reads the endpoint URL + token
/// that `agentstack mcp` writes next to it and POSTs each call there.
pub fn runtime_shim() -> &'static str {
    RUNTIME_SHIM
}

/// Convenience accessor: how a single tool is reached on the generated client,
/// e.g. `codemode.figma.get_file` or `codemode["claude-code"]["x"]`. Shared by
/// `tools_search` detail cards and `tools_bindings`.
pub fn access_path(server: &str, tool: &str) -> String {
    format!("codemode{}{}", member(server), member(tool))
}

/* ---------- TS rendering helpers ---------- */

const CLIENT_HEADER: &str = "\
// generated by `agentstack codemode` — do not edit.
// Typed client for this project's proxied MCP servers. Each function forwards to
// the local agentstack runtime endpoint, which resolves secrets and proxies the
// real upstream call. The bindings themselves are secret-free.
import { call } from \"./agentstack-runtime\";
";

const RUNTIME_SHIM: &str = "\
// generated by `agentstack codemode` — do not edit.
// Thin shim: every binding in client.ts calls through here. It POSTs
// { name, arguments } to the loopback runtime endpoint that `agentstack mcp`
// exposes; agentstack resolves ${REF}s and proxies the real upstream MCP call.
// No secrets live here — they are resolved server-side, per call.
import { readFileSync } from \"node:fs\";
import { fileURLToPath } from \"node:url\";

type Endpoint = { url: string; token: string };

function endpoint(): Endpoint {
  // `agentstack mcp` writes endpoint.json (machine-local: port + token) here.
  const path = fileURLToPath(new URL(\"./endpoint.json\", import.meta.url));
  try {
    return JSON.parse(readFileSync(path, \"utf8\")) as Endpoint;
  } catch {
    throw new Error(
      \"agentstack code-mode endpoint not found — run `agentstack mcp` in this project first \" +
        \"(it writes .agentstack/codemode/endpoint.json).\",
    );
  }
}

export async function call(name: string, args: unknown): Promise<unknown> {
  const { url, token } = endpoint();
  const res = await fetch(url, {
    method: \"POST\",
    headers: { \"Content-Type\": \"application/json\", \"X-Agentstack-Token\": token },
    body: JSON.stringify({ name, arguments: args ?? {} }),
  });
  const body = (await res.json().catch(() => ({}))) as { result?: unknown; error?: string };
  if (!res.ok || body.error) {
    throw new Error(`agentstack runtime: ${body.error ?? res.status}`);
  }
  return body.result;
}
";

/// A one-line, `*/`-safe JSDoc body from a (possibly multi-line, capped)
/// upstream description.
fn jsdoc(desc: &str) -> String {
    let collapsed: String = desc.split_whitespace().collect::<Vec<_>>().join(" ");
    collapsed.replace("*/", "* /")
}

/// Inline TS type for a tool's input, derived from the top-level `properties` of
/// its JSON Schema. Best-effort and shallow: nested shapes degrade to `unknown`.
fn ts_input_type(schema: &Value) -> String {
    let Some(props) = schema.get("properties").and_then(Value::as_object) else {
        return "Record<string, unknown>".to_string();
    };
    if props.is_empty() {
        return "Record<string, unknown>".to_string();
    }
    let required: Vec<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|a| a.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let fields: Vec<String> = props
        .iter()
        .map(|(k, v)| {
            let opt = if required.contains(&k.as_str()) {
                ""
            } else {
                "?"
            };
            format!("{}{}: {}", quote_key(k), opt, ts_type(v))
        })
        .collect();
    format!("{{ {} }}", fields.join("; "))
}

/// Map a JSON Schema property to a shallow TS type.
fn ts_type(prop: &Value) -> &'static str {
    match prop.get("type").and_then(Value::as_str) {
        Some("string") => "string",
        Some("number") | Some("integer") => "number",
        Some("boolean") => "boolean",
        Some("array") => "unknown[]",
        Some("object") => "Record<string, unknown>",
        _ => "unknown",
    }
}

/// Quote an object key unless it is already a valid JS identifier.
fn quote_key(s: &str) -> String {
    if is_ident(s) {
        s.to_string()
    } else {
        format!("{s:?}")
    }
}

/// `.foo` for an identifier, `["weird-name"]` otherwise.
fn member(s: &str) -> String {
    if is_ident(s) {
        format!(".{s}")
    } else {
        format!("[{s:?}]")
    }
}

fn is_ident(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' || c == '$' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn fixture() -> Vec<Value> {
        vec![
            json!({ "name": "figma__get_file", "description": "[via figma] Get a file's node tree.", "inputSchema": { "type": "object", "properties": { "fileKey": { "type": "string" }, "depth": { "type": "integer" } }, "required": ["fileKey"] } }),
            json!({ "name": "github__list_issues", "description": "[via github] List issues.", "inputSchema": { "type": "object" } }),
        ]
    }

    #[test]
    fn renders_typed_secret_free_client() {
        let ts = render_client(&fixture());
        // Grouped under codemode, addressed by server then tool.
        assert!(ts.contains("export const codemode = {"));
        assert!(ts.contains("figma: {"));
        assert!(ts.contains("github: {"));
        // Typed input from the schema; required vs optional honored.
        assert!(ts.contains("fileKey: string"));
        assert!(ts.contains("depth?: number"));
        // Forwards by namespaced name through the shim.
        assert!(ts.contains(r#"call("figma__get_file", input)"#));
        // Schema-less tool degrades to a permissive record.
        assert!(ts.contains("input: Record<string, unknown>"));
        // Secret-free: no resolved values, no ${REF} tokens.
        assert!(!ts.contains("${"));
        assert!(!ts.to_lowercase().contains("authorization"));
    }

    #[test]
    fn generation_is_deterministic_and_sorted() {
        // Reversed input still renders figma before github, get_file before nothing.
        let mut rev = fixture();
        rev.reverse();
        assert_eq!(render_client(&fixture()), render_client(&rev));
        let ts = render_client(&fixture());
        assert!(ts.find("figma:").unwrap() < ts.find("github:").unwrap());
    }

    #[test]
    fn empty_surface_renders_empty_client() {
        let ts = render_client(&[]);
        assert!(ts.contains("export const codemode = {};"));
    }

    #[test]
    fn access_path_handles_weird_names() {
        assert_eq!(access_path("figma", "get_file"), "codemode.figma.get_file");
        assert_eq!(
            access_path("claude-code", "do-thing"),
            "codemode[\"claude-code\"][\"do-thing\"]"
        );
    }

    #[test]
    fn jsdoc_is_single_line_and_safe() {
        assert_eq!(jsdoc("a\n  b   c"), "a b c");
        assert_eq!(jsdoc("end */ inject"), "end * / inject");
    }
}
